silverpop.silverpop_event_type.*:
  type: config_entity
  label: 'Silverpop Event Type'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: string
      label: 'Label'
    event_type:
      type: string
      label: 'Event type'
    css_selector:
      type: string
      label: 'CSS selector'
    page_visibility:
      type: string
      label: 'Page visibility'
    page_request_path:
      type: string
      label: 'Page request path'
    data:
      type: array
      label: 'Data'
